// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: bibliotecadn/DataNodeServer.proto

package bibliotecadn

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Mensajes necesarios para implementar la red
type UploadBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre    string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Chunkdata []byte `protobuf:"bytes,2,opt,name=chunkdata,proto3" json:"chunkdata,omitempty"`
}

func (x *UploadBookRequest) Reset() {
	*x = UploadBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBookRequest) ProtoMessage() {}

func (x *UploadBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBookRequest.ProtoReflect.Descriptor instead.
func (*UploadBookRequest) Descriptor() ([]byte, []int) {
	return file_bibliotecadn_DataNodeServer_proto_rawDescGZIP(), []int{0}
}

func (x *UploadBookRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *UploadBookRequest) GetChunkdata() []byte {
	if x != nil {
		return x.Chunkdata
	}
	return nil
}

type UploadBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta string `protobuf:"bytes,1,opt,name=respuesta,proto3" json:"respuesta,omitempty"`
}

func (x *UploadBookResponse) Reset() {
	*x = UploadBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBookResponse) ProtoMessage() {}

func (x *UploadBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBookResponse.ProtoReflect.Descriptor instead.
func (*UploadBookResponse) Descriptor() ([]byte, []int) {
	return file_bibliotecadn_DataNodeServer_proto_rawDescGZIP(), []int{1}
}

func (x *UploadBookResponse) GetRespuesta() string {
	if x != nil {
		return x.Respuesta
	}
	return ""
}

type PartName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
}

func (x *PartName) Reset() {
	*x = PartName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartName) ProtoMessage() {}

func (x *PartName) ProtoReflect() protoreflect.Message {
	mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartName.ProtoReflect.Descriptor instead.
func (*PartName) Descriptor() ([]byte, []int) {
	return file_bibliotecadn_DataNodeServer_proto_rawDescGZIP(), []int{2}
}

func (x *PartName) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type PartChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunkdata []byte `protobuf:"bytes,1,opt,name=chunkdata,proto3" json:"chunkdata,omitempty"`
}

func (x *PartChunk) Reset() {
	*x = PartChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartChunk) ProtoMessage() {}

func (x *PartChunk) ProtoReflect() protoreflect.Message {
	mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartChunk.ProtoReflect.Descriptor instead.
func (*PartChunk) Descriptor() ([]byte, []int) {
	return file_bibliotecadn_DataNodeServer_proto_rawDescGZIP(), []int{3}
}

func (x *PartChunk) GetChunkdata() []byte {
	if x != nil {
		return x.Chunkdata
	}
	return nil
}

//Mensaje para la implementacion del alg. Distribuido
type Propuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunksadn1   int64 `protobuf:"varint,1,opt,name=chunksadn1,proto3" json:"chunksadn1,omitempty"`
	Chunksadn2   int64 `protobuf:"varint,2,opt,name=chunksadn2,proto3" json:"chunksadn2,omitempty"`
	Chunksadn3   int64 `protobuf:"varint,3,opt,name=chunksadn3,proto3" json:"chunksadn3,omitempty"`
	Ipaverificar int64 `protobuf:"varint,4,opt,name=ipaverificar,proto3" json:"ipaverificar,omitempty"`
}

func (x *Propuesta) Reset() {
	*x = Propuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Propuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Propuesta) ProtoMessage() {}

func (x *Propuesta) ProtoReflect() protoreflect.Message {
	mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Propuesta.ProtoReflect.Descriptor instead.
func (*Propuesta) Descriptor() ([]byte, []int) {
	return file_bibliotecadn_DataNodeServer_proto_rawDescGZIP(), []int{4}
}

func (x *Propuesta) GetChunksadn1() int64 {
	if x != nil {
		return x.Chunksadn1
	}
	return 0
}

func (x *Propuesta) GetChunksadn2() int64 {
	if x != nil {
		return x.Chunksadn2
	}
	return 0
}

func (x *Propuesta) GetChunksadn3() int64 {
	if x != nil {
		return x.Chunksadn3
	}
	return 0
}

func (x *Propuesta) GetIpaverificar() int64 {
	if x != nil {
		return x.Ipaverificar
	}
	return 0
}

type Okrespondido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Okay bool `protobuf:"varint,1,opt,name=okay,proto3" json:"okay,omitempty"`
}

func (x *Okrespondido) Reset() {
	*x = Okrespondido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Okrespondido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Okrespondido) ProtoMessage() {}

func (x *Okrespondido) ProtoReflect() protoreflect.Message {
	mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Okrespondido.ProtoReflect.Descriptor instead.
func (*Okrespondido) Descriptor() ([]byte, []int) {
	return file_bibliotecadn_DataNodeServer_proto_rawDescGZIP(), []int{5}
}

func (x *Okrespondido) GetOkay() bool {
	if x != nil {
		return x.Okay
	}
	return false
}

type Ricart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Id int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Ricart) Reset() {
	*x = Ricart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ricart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ricart) ProtoMessage() {}

func (x *Ricart) ProtoReflect() protoreflect.Message {
	mi := &file_bibliotecadn_DataNodeServer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ricart.ProtoReflect.Descriptor instead.
func (*Ricart) Descriptor() ([]byte, []int) {
	return file_bibliotecadn_DataNodeServer_proto_rawDescGZIP(), []int{6}
}

func (x *Ricart) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Ricart) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_bibliotecadn_DataNodeServer_proto protoreflect.FileDescriptor

var file_bibliotecadn_DataNodeServer_proto_rawDesc = []byte{
	0x0a, 0x21, 0x62, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x74, 0x65, 0x63, 0x61, 0x64, 0x6e, 0x2f, 0x44,
	0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x64, 0x61, 0x74, 0x61, 0x22, 0x32,
	0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x22, 0x22, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22, 0x29, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x8f, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x61, 0x64, 0x6e, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x61, 0x64, 0x6e, 0x31, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x61, 0x64, 0x6e, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x61, 0x64, 0x6e, 0x32, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x61, 0x64, 0x6e, 0x33, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x61, 0x64, 0x6e, 0x33, 0x12,
	0x22, 0x0a, 0x0c, 0x69, 0x70, 0x61, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x69, 0x70, 0x61, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x72, 0x22, 0x22, 0x0a, 0x0c, 0x4f, 0x6b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64,
	0x69, 0x64, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x6b, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x6f, 0x6b, 0x61, 0x79, 0x22, 0x28, 0x0a, 0x06, 0x52, 0x69, 0x63, 0x61, 0x72,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x32, 0xf3, 0x02, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x16, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42,
	0x6f, 0x6f, 0x6b, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x12,
	0x12, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x44, 0x0a, 0x15,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x69, 0x64, 0x6f, 0x12, 0x12, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6f,
	0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x12, 0x3d, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x12, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x12, 0x2b, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6f, 0x6f,
	0x6b, 0x12, 0x09, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x0a, 0x2e, 0x50,
	0x61, 0x72, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x37,
	0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x69, 0x64, 0x61, 0x12, 0x0a, 0x2e, 0x50, 0x72, 0x6f,
	0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x1a, 0x0d, 0x2e, 0x4f, 0x6b, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x64, 0x69, 0x64, 0x6f, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x12, 0x07, 0x2e,
	0x52, 0x69, 0x63, 0x61, 0x72, 0x74, 0x1a, 0x0d, 0x2e, 0x4f, 0x6b, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x64, 0x69, 0x64, 0x6f, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x62, 0x75, 0x2f, 0x74,
	0x61, 0x72, 0x65, 0x61, 0x32, 0x73, 0x64, 0x2f, 0x62, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x74, 0x65,
	0x63, 0x61, 0x64, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bibliotecadn_DataNodeServer_proto_rawDescOnce sync.Once
	file_bibliotecadn_DataNodeServer_proto_rawDescData = file_bibliotecadn_DataNodeServer_proto_rawDesc
)

func file_bibliotecadn_DataNodeServer_proto_rawDescGZIP() []byte {
	file_bibliotecadn_DataNodeServer_proto_rawDescOnce.Do(func() {
		file_bibliotecadn_DataNodeServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_bibliotecadn_DataNodeServer_proto_rawDescData)
	})
	return file_bibliotecadn_DataNodeServer_proto_rawDescData
}

var file_bibliotecadn_DataNodeServer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bibliotecadn_DataNodeServer_proto_goTypes = []interface{}{
	(*UploadBookRequest)(nil),  // 0: UploadBookRequest
	(*UploadBookResponse)(nil), // 1: UploadBookResponse
	(*PartName)(nil),           // 2: PartName
	(*PartChunk)(nil),          // 3: PartChunk
	(*Propuesta)(nil),          // 4: Propuesta
	(*Okrespondido)(nil),       // 5: Okrespondido
	(*Ricart)(nil),             // 6: Ricart
}
var file_bibliotecadn_DataNodeServer_proto_depIdxs = []int32{
	0, // 0: DataNodeService.UploadBookCentralizado:input_type -> UploadBookRequest
	0, // 1: DataNodeService.UploadBookDistribuido:input_type -> UploadBookRequest
	0, // 2: DataNodeService.DistributeBook:input_type -> UploadBookRequest
	2, // 3: DataNodeService.DownloadBook:input_type -> PartName
	4, // 4: DataNodeService.SendPropuestaDistribuida:input_type -> Propuesta
	6, // 5: DataNodeService.RequestCompetencia:input_type -> Ricart
	1, // 6: DataNodeService.UploadBookCentralizado:output_type -> UploadBookResponse
	1, // 7: DataNodeService.UploadBookDistribuido:output_type -> UploadBookResponse
	1, // 8: DataNodeService.DistributeBook:output_type -> UploadBookResponse
	3, // 9: DataNodeService.DownloadBook:output_type -> PartChunk
	5, // 10: DataNodeService.SendPropuestaDistribuida:output_type -> Okrespondido
	5, // 11: DataNodeService.RequestCompetencia:output_type -> Okrespondido
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bibliotecadn_DataNodeServer_proto_init() }
func file_bibliotecadn_DataNodeServer_proto_init() {
	if File_bibliotecadn_DataNodeServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bibliotecadn_DataNodeServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bibliotecadn_DataNodeServer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bibliotecadn_DataNodeServer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bibliotecadn_DataNodeServer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bibliotecadn_DataNodeServer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Propuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bibliotecadn_DataNodeServer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Okrespondido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bibliotecadn_DataNodeServer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ricart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bibliotecadn_DataNodeServer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bibliotecadn_DataNodeServer_proto_goTypes,
		DependencyIndexes: file_bibliotecadn_DataNodeServer_proto_depIdxs,
		MessageInfos:      file_bibliotecadn_DataNodeServer_proto_msgTypes,
	}.Build()
	File_bibliotecadn_DataNodeServer_proto = out.File
	file_bibliotecadn_DataNodeServer_proto_rawDesc = nil
	file_bibliotecadn_DataNodeServer_proto_goTypes = nil
	file_bibliotecadn_DataNodeServer_proto_depIdxs = nil
}
